---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: op-wx-api
  namespace: prod
---
apiVersion: v1
kind: Service
metadata:
  name: op-wx-api
  namespace: prod
spec:
  ports:
    - name: http
      targetPort: 8001
      port: 80
  selector:
    app: op-wx-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: op-wx-api
  namespace: prod
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: op-wx-api
  template:
    metadata:
      labels:
        app: op-wx-api
    spec:
      restartPolicy: Always
      serviceAccountName: op-wx-api
      containers:
        - name: op-wx-api
          image: harbor-public.123go.club:9443/test/op-wx-api:v1
          command:
            - sh
            - -c
            - sleep 1 && ./main start
          imagePullPolicy: IfNotPresent
          env:
            - name: GIN_MODE
              value: release
            - name: LOG_LEVEL
              value: DEBUG
            - name: RUNTIME_ENV
              value: "public"
            - name: RUNTIME_GROUP
              value: "ops"
            - name: RUNTIME_APP_NAME
              value: "op-wx-api"
            - name: RUNTIME_CONFIG_URL
              value: "http://82.156.241.153"
          resources:
            limits:
              cpu: "1"
              memory: 500M
            requests:
              cpu: "1"
              memory: 500M
